blank_issues_enabled: true
contact_links:
  - name: 问题提问 | Ask a question (GitHub Discussions)
    url: https://github.com/tryzealot/zealot/discussions
    about: 所有问题会放在 GitHub Discussions，GitHub issues 仅提供缺陷追踪和新特性相关，但我保留不回答的权利 | We use GitHub Discussions for questions, GitHub issues for tracking bug reports and feature requests
  - name: 私下技术沟通 | Chat with developer
    url: https://github.com/tryzealot/zealot
    about: 别想了！就算你找到我了，我也不会给予任何回复！开发者会在在本页面上述反馈方式进行回复 | No way!