lane :version_check do
  zealot_version_check(
    endpoint: 'http://localhost:3000',
    token: '...',
    bundle_id: 'com.example.app.name'
    release_version: '1.0.0',
    build_version: '1'
  )
end

lane :upload_app do
  zealot(
    endpoint: 'http://localhost:3000',
    token: '...',
    channel_key: '...',
    file: 'app.apk'
  )
end

# lane :upload_debug_file do
#   zealot_debug_file(
#     endpoint: 'http://localhost:3000',
#     token: '...',
#     channel_key: '...',
#     file: 'app.apk'
#   )
# end
