lane :version_check do
  zealot_version_check(
    endpoint: 'http://localhost:3000',
    token: '...',
    bundle_id: 'com.example.app.name',
    release_version: '1.0.0',
    build_version: '1'
  )
end

lane :sync_devices do
  zealot_sync_devices(
    endpoint: 'http://localhost:3000',
    token: '...',
    username: '...',
    team_id: '...'
  )
end

lane :upload_app do
  zealot(
    endpoint: 'http://localhost:3000',
    token: '...',
    channel_key: '...',
    file: 'app.apk'
  )
end

lane :upload_debug_file do
  zealot_debug_file(
    endpoint: 'http://localhost:3000',
    token: '...',
    channel_key: '...',
    platform: :ios,
    xcode_scheme: 'AppName',
    overwrite: true
  )

  zealot_debug_file(
    endpoint: 'http://localhost:3000',
    token: '...',
    channel_key: '...',
    platform: :android,
    android_build_type: 'release',
    android_flavor: 'store',
    overwrite: true
  )
end

lane :sync do
  zealot_sync_devices(
    endpoint: 'http://localhost:3000',
    token: '320bacf980e20e7b058be2d77154dc53',
    username: 'icyleaf@ews.im'
  )
end
